### ISSUE TITLE
Create Sounds CRUD

### ISSUE THREAD

**Issue by veganstraightedge** [homesteading/homesteading-server-rails#7]
```ruby
text:     "title"
text:     "subtitle"
text:     "content"
text:     "slug"
text:     "in_reply_to"
text:     "tags"
datetime: "published_at"
boolean:  "private"
text:     "image_url"
text:     "sound_url"
datetime: "recorded_at"
```

**Comment by veganstraightedge** [comment]
Videos and Sounds both have a `thing_url` with their respective names (video_ and sound_).
Should we generalize this to be the same across both? 

If so, here's some noun ideas:
- source_url (though `source_*` seems to be what people are using to say "the app that this was published with)
- attachment_url (like an email)
- enclosure_url (this is what rss and atom call their files in podcasts)

Of these, I leaning toward enclosure_url.

**Comment by veganstraightedge** [comment]
Videos (#6)  and Sounds both have a `thing_url` with their respective names (video_ and sound_).
Should we generalize this to be the same across both? 

If so, here's some noun ideas:
- source_url (though `source_*` seems to be what people are using to say "the app that this was published with)
- attachment_url (like an email)
- enclosure_url (this is what rss and atom call their files in podcasts)

Of these, I leaning toward enclosure_url.

**Comment by veganstraightedge** [comment]
I decided to go with `enclosure_url`

**Comment by veganstraightedge** [comment]
Same goes for `Photo#taken_at`, `Video#taken_at` and `Sound#recorded_at`.
I'd sure like to find a verb that works for all three (and isn't `created_at`).

@bookis ideas?

**Comment by bookis** [comment]
`#captured_at`?

**Comment by veganstraightedge** [comment]
That's pretty good. I'll update them.
