### ISSUE TITLE
Add pagination to homepage

### ISSUE THREAD

**Issue by veganstraightedge** [homesteading/homesteading-server-rails#78]
After #65 is done, use `will_paginate` on homepage too.

https://github.com/mislav/will_paginate

Right now, because the composite feed isn't a real ActiveRelation/ActiveModel collection, `will_paginate` doesn't Just Work™. After there's a Post model and we can do `Post.all`, `will_paginate` will Do The Right Thing™.

**Comment by bookis** [comment]
Maybe use: https://github.com/amatsuda/kaminari

**Comment by veganstraightedge** [comment]
Depends on #65
